### ISSUE TITLE
container: Dockge

### ISSUE THREAD

**Issue by faz-adi** [ajnart/docker-compose-maker#23]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

47fb5d816385

### Display Name

Dockge

### Description

A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager

### Category

Management

### Tags

Management, UI, Monitoring

### GitHub URL

https://github.com/louislam/dockge/

### Docker Compose Service Definition

```yaml
services:
  dockge:
    container_name: ${CONTAINER_PREFIX}dockge
    image: louislam/dockge:1
    restart: ${RESTART_POLICY}
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/data:/app/data
      - ${DATA_PATH}/stacks:/opt/stacks
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_ENABLE_CONSOLE=true
```
