### ISSUE TITLE
container: Arcane

### ISSUE THREAD

**Issue by seanbf** [ajnart/docker-compose-maker#31]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

arcane

### Display Name

Arcane

### Description

Arcane is a Simple and Elegant Docker Management UI written in Typescript and SvelteKit. It aims to provide an intuitive interface for managing your Docker containers, images, volumes, and networks.

### Category

Management

### Tags

UI, Management, Manager, Network, Statistics, Dashboard

### GitHub URL

https://github.com/ofkm/arcane

### Icon URL

https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/arcane.svg

### Docker Compose Service Definition

```yaml
services:
  arcane:
    container_name: ${CONTAINER_PREFIX:-arcane}
    image: ${IMAGE_ARCANE:-ghcr.io/ofkm/arcane:latest}
    ports:
      - "${ARCANE_PORT:-3000}:3000"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - APP_ENV=${APP_ENV:-production}
      - PUBLIC_SESSION_SECRET=${PUBLIC_SESSION_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_PATH:-/mnt/user/appdata/arcane}:/app/data
      - ${DOCKER_STACKS_PATH:-/opt/my-docker-stacks}:/opt/my-docker-stacks:ro
    restart: ${RESTART_POLICY:-unless-stopped}
```

### Additional Information

Need to generate: openssl rand -base64 32
