### ISSUE TITLE
RomM

### ISSUE THREAD

**Issue by thedemobro2** [ajnart/docker-compose-maker#6]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

RomM

### Display Name

RomM

### Description

Rom Manager

### Category

Media

### Tags

Rom, emulator, management software,  

### GitHub URL (Optional)

https://github.com/rommapp

### Docker Compose Service Definition

```yaml
services:
  romm-mariadb-dev:
    image: mariadb:11.3.2
    container_name: romm-mariadb-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASSWD
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PASSWD
    volumes:
      - maria-db:/var/lib/mysql
    ports:
      - $DB_PORT:3306

  romm-valkey-dev:
    image: valkey/valkey:8
    container_name: romm-valkey-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $REDIS_PORT:6379

  romm-postgres-dev:
    image: docker.io/library/postgres:16-alpine
    container_name: romm-postgresql-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  romm-authentik-server:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: romm-authentik-server
    restart: unless-stopped
    command: server
    env_file:
      - .env
    environment:
      AUTHENTIK_REDIS__HOST: romm-valkey-dev
      AUTHENTIK_POSTGRESQL__HOST: romm-postgres-dev
      AUTHENTIK_POSTGRESQL__USER: $POSTGRES_USER
      AUTHENTIK_POSTGRESQL__NAME: $POSTGRES_DB
      AUTHENTIK_POSTGRESQL__PASSWORD: $POSTGRES_PASSWORD
      AUTHENTIK_SECRET_KEY: $AUTHENTIK_SECRET_KEY
      AUTHENTIK_BOOTSTRAP_PASSWORD: $AUTHENTIK_BOOTSTRAP_PASSWORD
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    ports:
      - 9001:9000
      - 9444:9443
    depends_on:
      - romm-postgres-dev
      - romm-valkey-dev

  romm-authentik-worker:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: romm-authentik-worker
    restart: unless-stopped
    command: worker
    env_file:
      - .env
    environment:
      AUTHENTIK_REDIS__HOST: romm-valkey-dev
      AUTHENTIK_POSTGRESQL__HOST: romm-postgres-dev
      AUTHENTIK_POSTGRESQL__USER: $POSTGRES_USER
      AUTHENTIK_POSTGRESQL__NAME: $POSTGRES_DB
      AUTHENTIK_POSTGRESQL__PASSWORD: $POSTGRES_PASSWORD
      AUTHENTIK_SECRET_KEY: $AUTHENTIK_SECRET_KEY
      AUTHENTIK_BOOTSTRAP_PASSWORD: $AUTHENTIK_BOOTSTRAP_PASSWORD
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    depends_on:
      - romm-postgres-dev
      - romm-valkey-dev

volumes:
  maria-db:
  postgres-db:
  authentik-media:
  authentik-templates:
```
